/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "b2eab7500a18bd4d372f10149c6223fdfe48e3be"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
