/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "273bf7ac8c909cde36982d27f66f3c70846a3718"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
