/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "adefa7837d02a07a604c1e6eff0b3a09422ab88d"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
