/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "1195e70d671947af02a6a5b0ddc65806b9645252"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
