/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "b4d28b2f35396ae4dd69338254415066629dfd25"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
