/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "93e7d305c32c17b3fa3e531dd967bc588948a080"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
