
SRC= \
src/searchr.c\
src/search.c\
src/repeat.c\
src/next.c\
src/nextr.c\
src/history.c\
src/nexte.c\
src/quiesce.c\
src/evaluate.c\
src/movgen.c\
src/make.c\
src/unmake.c\
src/lookup.c\
src/store.c\
src/attacks.c\
src/swap.c\
src/boolean.c\
src/draw.c\
src/utility.c\
src/valid.c\
src/drawn.c\
src/edit.c\
src/enprise.c\
src/init.c\
src/input.c\
src/interupt.c\
src/iterate.c\
src/main.c\
src/option.c\
src/output.c\
src/phase.c\
src/ponder.c\
src/preeval.c\
src/root.c\
src/setboard.c\
src/time.c\
src/validate.c

IT=crafty
CFLAGS_EXTRA = -DSPEC_CPU2000 -DLINUX_i386
EMCCFLAGS_EXTRA_TRAIN =
EMCCFLAGS_EXTRA_REF =

EXTRA_CLEAN=game.*

include ../Makefile.common
